# Generated by Django 4.0.2 on 2022-02-04 12:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Cosme Fulanito', max_length=50)),
                ('phone_number', phone_field.models.PhoneField(default='00000000', max_length=31)),
                ('contact_email', models.EmailField(default='empty@cc.com', max_length=254)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('favorite', models.BooleanField(default=False)),
                ('filed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
