# Generated by Django 3.0.7 on 2022-02-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactfield',
            name='phone_number',
        ),
    ]
