# Generated by Django 3.0.7 on 2022-02-03 21:45

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contactfield_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactfield',
            name='phone_number',
            field=phone_field.models.PhoneField(default='00000000', max_length=31),
        ),
    ]
